name: obod_shahar
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  adaptive_theme: ^3.1.1
  sqflite: ^2.2.3
  cached_network_image: ^3.2.2
  change_app_package_name: ^1.1.0
  cloud_firestore: ^4.1.0
  connectivity_plus: ^2.3.7
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dotted_border: ^2.0.0+2
  easy_localization: ^3.0.1
  email_validator: ^2.1.16
  equatable: ^2.0.5
  file_picker: ^5.0.1
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.1
  firebase_storage: ^11.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_linkify: ^5.0.2
  flutter_local_notifications: ^12.0.2
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.6.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.1+1
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  formz: ^0.4.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.1
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  json_serializable: ^6.3.1
  lottie: ^1.4.3
  mask_text_input_formatter: ^2.3.0
  meta: ^1.7.0
  modal_bottom_sheet: ^2.0.1
  nfc_manager: ^3.2.0
  open_filex: ^4.1.1
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0
  url_launcher: ^6.1.4
  firebase_auth: ^4.2.5
  zoom_tap_animation: ^1.1.0
  keyboard_dismisser: ^3.0.0
  animated_snack_bar: ^0.3.0
  google_sign_in: ^5.4.3
  stop_watch_timer: ^2.0.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/svg/
    - assets/svg/action/
    - assets/svg/alert/
    - assets/svg/av/
    - assets/svg/card/
    - assets/svg/communication/
    - assets/svg/content/
    - assets/svg/content/appointment_empty.svg
    - assets/svg/device/
    - assets/svg/editor/
    - assets/svg/file/
    - assets/svg/hardware/
    - assets/svg/image/
    - assets/svg/maps/
    - assets/svg/navigation/
    - assets/svg/notification/
    - assets/svg/social/
    - assets/svg/specialist/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: SourceSansPro-Black
      fonts:
        - asset: assets/fonts/SourceSansPro-Black.ttf
    - family: SourceSansPro-Bold
      fonts:
        - asset: assets/fonts/SourceSansPro-Bold.ttf
    - family: SourceSansPro-Light
      fonts:
        - asset: assets/fonts/SourceSansPro-Light.ttf
    - family: SourceSansPro-Regular
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
    - family: SourceSansPro-Semibold
      fonts:
        - asset: assets/fonts/SourceSansPro-Semibold.ttf
